use_frameworks!

target 'NaruiUIComponents_Example' do
  pod 'NaruiUIComponents', :path => '../'

  target 'NaruiUIComponents_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
    pod 'UBottomSheet'
    pod 'RxCocoa'
    pod 'RxSwift'
    pod 'PhoneNumberKit'
    pod 'RxKingfisher'
    pod 'AlamofireImage'
    pod 'MKRingProgressView'

  end
end
